name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ Pooja755 }}
          password: ${{ Pooja@1234 }}

      - name: Build Docker image
        run: docker build -t pooja755/buzzzworth-app:latest .

      - name: Push Docker image
        run: docker push pooja755/buzzzworth-app:latest
